version: "3"

services:
  travis:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - ./.travis:/root/.travis
    network_mode: bridge

  rcmoutinho-travis:
    image: rcmoutinho/travis-cli
    volumes:
      - .:/app
      - ./.travis:/root/.travis
    network_mode: bridge
